### ISSUE TITLE
How to keep this repo up-to-date with the original version?

### ISSUE THREAD

**Issue by linhe0x0** [iliakan/javascript-tutorial-cn#2]
Should we create a new branch and work on this new branch? @iliakan

**Comment by iliakan** [comment]
This is cn-only repo.

As of now it's a fork of tutorial-en, so you can pull updates from there, and skip things that you already translated.

The tutorial is mostly stable, ready to be translated.

**Comment by iliakan** [comment]
P.S. So you can work here, maybe create branches for your own comfort and synchronization.
